# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

[zh-Hant]
  languageCode = "zh-Hant"
  contentDir = "content/zh-Hant"
  title = "Hsiang-Chu Chou"
  [zh-Hant.params]
    contact_links = [
      {icon = "envelope", icon_pack = "fas", name = "xcjocjo@gmail.com", link = "mailto:xcjocjo@gmail.com"},
      {icon = "phone-volume", icon_pack = "fas", name = "886-919-395038", link = "tel:+886919395038"},
      {icon = "linkedin", icon_pack = "fab", name = "DM Me", link = "https://www.linkedin.com/in/huahcc/"},
      {icon = "weixin", icon_pack = "fab", name = "xcjocjo", link = ""},
      ]
  [[zh-Hant.menu.main]]
  	name = "關於我"
  	url = "#about"
  	weight = 10
  [[zh-Hant.menu.main]]
  	name = "技能"
  	url = "#skills"
  	weight = 20
  [[zh-Hant.menu.main]]
  	name = "經歷"
  	url = "#work-experience"
  	weight = 40
  [[zh-Hant.menu.main]]
  	name = "專案"
  	url = "#project-experience"
  	weight = 50
  [[zh-Hant.menu.main]]
    name = "競賽"
    url = "#accomplishments"
    weight = 55
  [[zh-Hant.menu.main]]
  	name = "聯絡資訊"
  	url = "#contact"
  	weight = 60
  [[zh-Hant.menu.main]]
    name = "簡歷"
    url = "files/HsiangChuChou-zh.pdf"
    weight = 100
